# Generated by Django 5.0.4 on 2024-04-12 08:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_alter_patient_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bill',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='insurance_claim',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='insurance_company',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medicalimage',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='test_result',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='treatmentplan',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False, primary_key=True, serialize=False),
        ),
    ]
