# Generated by Django 5.0.4 on 2024-04-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_alter_appointment_id_alter_appointmentrequest_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrequest',
            name='preferred_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='preferred_time',
            field=models.TimeField(),
        ),
    ]
