# Generated by Django 5.0.4 on 2024-04-13 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0024_alter_appointmentrequest_preferred_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='reason_of_visit',
        ),
        migrations.AddField(
            model_name='appointment',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.appointmentrequest'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
