# Generated by Django 5.0.4 on 2024-04-14 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0025_remove_appointment_reason_of_visit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
