# Generated by Django 5.0.4 on 2024-04-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0027_alter_test_result_test_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalimage',
            name='updated_on',
            field=models.DateTimeField(),
        ),
    ]
