# Generated by Django 5.0.4 on 2024-04-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0028_alter_medicalimage_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentplan',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='treatmentplan',
            name='start_date',
            field=models.DateField(),
        ),
    ]
