# Generated by Django 5.0.4 on 2024-04-16 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0031_extendeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='department',
            field=models.CharField(choices=[('Patient Management', 'Patient Management'), ('Records Management', 'Records Management'), ('Financial Management', 'Financial Management')], default='', max_length=20),
        ),
    ]
