# Generated by Django 5.0.4 on 2024-04-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0032_extendeduser_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='user_type',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Records', 'Records'), ('Finance', 'Finance')], default='', max_length=50),
        ),
    ]
